name: pinpoint1
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - _x86_64-microarch-level=4=3_cascadelake
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - awkward=2.8.12=pyhcf101f3_0
  - awkward-cpp=51=py313hd3cbb54_0
  - awkward-pandas=2023.8.0=pyhd8ed1ab_0
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.16.0=h75daedc_0
  - azure-storage-common-cpp=12.12.0=h3d7a050_0
  - azure-storage-files-datalake-cpp=12.14.0=hd454692_0
  - boost-histogram=1.7.1=py313hc8edb43_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - click=8.3.1=pyh8f84b5b_1
  - contourpy=1.3.3=py313hc8edb43_4
  - cpython=3.13.11=py313hd8ed1ab_101
  - cramjam=2.11.0=py313h7ef63f5_2
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cusparselt=0.7.0.0=hcd2ec93_0
  - cycler=0.12.1=pyhcf101f3_2
  - filelock=3.20.3=pyhd8ed1ab_0
  - fonttools=4.61.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_2
  - hepunits=2.4.4=pyhcf101f3_0
  - hist=2.10.0=pyhfd60d43_0
  - hist-base=2.10.0=pyhcf101f3_0
  - histoprint=2.6.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - iminuit=2.32.0=py313h5d5ffb9_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=23.0.0=h2c50142_1_cpu
  - libarrow-acero=23.0.0=h635bf11_1_cpu
  - libarrow-compute=23.0.0=h8c2c5c3_1_cpu
  - libarrow-dataset=23.0.0=h635bf11_1_cpu
  - libarrow-substrait=23.0.0=h3f74fd7_1_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - liblzma=5.8.2=hb03c661_0
  - libmagma=2.8.0=h566cb83_2
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=23.0.0=h7376487_1_cpu
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.7.1=cpu_generic_h1322af4_3
  - libudev1=258.3=h6569c3e_0
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning=2.6.0=pyhcf101f3_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=21.1.8=h4922eb0_0
  - llvmlite=0.46.0=py313hdd307be_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib-base=3.10.8=py313h683a580_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mplhep=0.4.1=pyhd8ed1ab_0
  - mplhep_data=0.0.5=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.63.1=py313h5dce7c4_0
  - numpy=2.3.5=py313hf6604e3_1
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.1=h35e630c_1
  - optree=0.18.0=py313h7037e92_0
  - orc=2.2.2=h19cb568_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py313hbfd7664_0
  - particle=0.26.1=pyhd8ed1ab_1
  - pillow=12.1.0=py313h80991f8_0
  - pip=26.0=pyh145f28c_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=23.0.0=py313h78bf25f_0
  - pyarrow-core=23.0.0=py313he109ebe_0_cpu
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - python=3.13.11=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-xxhash=3.6.0=py313heab5758_1
  - python_abi=3.13=8_cp313
  - pytorch=2.7.1=cpu_generic_py313_h33fc178_3
  - pytorch-lightning=2.6.1=pyhcf101f3_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - qhull=2020.2=h434a139_5
  - rdma-core=61.0=h192683f_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - s2n=1.6.2=he8a4886_1
  - scikit-learn=1.8.0=np2py313h16d504d_1
  - scipy=1.17.0=py313h4b8bb8b_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - sympy=1.14.0=pyh2585a3b_105
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h366c992_103
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - uhi=1.0.0=pyhcf101f3_1
  - uproot=5.7.1=pyhcf101f3_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - hydra-core==1.3.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - setuptools==80.10.2
      - torch==2.10.0
      - torchvision==0.25.0
      - triton==3.6.0
